### ISSUE TITLE
How to import Iconify JSON into app

### ISSUE THREAD

**Issue by chasegiunta** [iconify/tools#13]
What's the recommended way, after exporting a directory of icons to an iconify JSON file, to import that JSON file into your app for use? I would think to do `Iconify.addCollection(myCollectionFile);` but there's no easy way to import JSON files.

Should the tools export as a javascript file instead for easy module import?

**Comment by cyberalien** [comment]
I'm not sure what you are asking.

As I understand, you have JSON file. So just insert it in your document. If you are using SVG framework, wrap it in `Iconify.addCollection(contents of file)` and import that file in your document right after importing SVG framework.

This might help you: https://docs.iconify.design/sources/bundles/svg-framework.html

**Comment by chasegiunta** [comment]
@cyberalien The contents of the JSON file would be dynamic. This is a part of the Iconify process I wasn't sure how people were addressing for custom icons and the SVG framework.

Presumedly, every time we had to add custom icons to our app, we'd run a npm script that imports a directory of custom SVGs via `ImportDir('directory/of/icons')`, and exports that JSON collection out to a file via `ExportJSON('iconify-collection.json')`. We would then need to add that to our app on initialize via `Iconify.addCollection()`, but since we can't simply `import collection from 'iconify-collection.json'` since it's a JSON file, I'm not sure what we can do.

**Comment by chasegiunta** [comment]
@cyberalien Ah, okay. I see that you're manually writing the javascript file here:
```
then((json) => {
       // Export to bundle
       const text = JSON.stringify(json);
       const output = preload
           ? 'IconifyPreload = [' + text + '];\n'
           : 'Iconify.addCollection(' + text + ');\n';

       // Save to file
       fs.writeFileSync(target, output, 'utf8');

       console.log(`Saved ${target} (${output.length} bytes)`);
   })
   ```
  
   That's one way to do it 😅

**Comment by chasegiunta** [comment]
@cyberalien I was able to tweak your example into what we needed. I think this will work so I will close. Thank you for such a great library and your help. If you see any issues with what I'm trying to accomplish, please let me know!

**Comment by kathirr007** [comment]
@cyberalien / @cyberalien anyone please provide some working example to use the generated icons JSON file in vue project

**Comment by cyberalien** [comment]
This issue is old, for old part of project and is irrelevant. Don't use this code, use Unplugin Icons instead that generates Vue components.
