### ISSUE TITLE
No matching version found

### ISSUE THREAD

**Issue by Doclassif** [iconify/tools#20]
/var/www # npm i @iconify/tools --save-dev
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @iconify/utils@^2.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by cyberalien** [comment]
Probably a cache error in NPM. Run `npm cache clean --force`
