### ISSUE TITLE
Warning from svgo while installing `@iconify/tools`

### ISSUE THREAD

**Issue by jd-solanki** [iconify/tools#21]
Hi,
While using `@iconify/tools@2.1.0` we are getting an installation warning:
```
warning @iconify/tools > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
```
![Screenshot 2022-09-16 at 4 56 15 PM](https://user-images.githubusercontent.com/47495003/190628760-1bcffe0c-6dfe-44f7-b358-5a983e1d6430.png)

**Comment by cyberalien** [comment]
Thanks for reporting!

Unfortunately there is nothing I can do about it, it is a dependency of `svgo`, not tools. It has been reported to SVGO repository: https://github.com/svg/svgo/issues/1689 and PR is waiting to be merged.
