### ISSUE TITLE
Importing @iconify/tools fails

### ISSUE THREAD

**Issue by markus-li** [iconify/tools#22]
When importing @iconify/tools into a TypeScript project it fails:

```
Could not find a declaration file for module '@iconify/tools'. './node_modules/.pnpm/@iconify+tools@2.1.1_@iconify+types@2.0.0/node_modules/@iconify/tools/lib/index.mjs' implicitly has an 'any' type.
```

The simple fix is to add:
```
"types": "./lib/index.d.ts"
```

to package.json:
```
"exports": {
		"./*": "./*",
		".": {
			"require": "./lib/index.cjs",
			"import": "./lib/index.mjs",
			"types": "./lib/index.d.ts"
		},
```

**Comment by cyberalien** [comment]
What node and typescript versions are you using?

**Comment by markus-li** [comment]
nodejs: v16.18.1
tsc: 4.8.4

**Comment by markus-li** [comment]
Some relevant documentation:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#ecmascript-module-support-in-node-js
https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

**Comment by cyberalien** [comment]
Thanks. I've published update that fixes it.

Weird thing is, I'm not getting such errors in any of my dev environments, including same versions of node and typescript as you are using. Can you please tell me if latest version fixes error message?

**Comment by markus-li** [comment]
Maybe it's related to the fact I'm using pnpm? There's a couple of oddities with pnpm and Typescript still.
It works now, I just realize that so far this fix didn't seem to be enough for VSCode to pickup the type definitions. Restarting VSCode fixed that.

**Comment by cyberalien** [comment]
Could be.

Thanks a lot for checking and for reporting issue!
