### ISSUE TITLE
svgo upgrade to 3.0.2?

### ISSUE THREAD

**Issue by markus-li** [iconify/tools#23]
Since the current version of svgo doesn't use native stable sort, maybe you could consider upgrading to svgo 3.0.2? It does require node.js 14+, so that may be a breaking change depending on how you run it.
Another bonus is that types are now included since 3.0.2.

https://github.com/svg/svgo/releases

**Comment by cyberalien** [comment]
Upgraded.

Expected to see many errors, but surprisingly there were just few minor issues. Didn't notice any difference in SVGO behaviour.

It will be published as `2.2.0-beta.1` version later, currently fighting with SvelteKit demo that just refuses to work and throws bunch of illogical errors.

**Comment by cyberalien** [comment]
After testing it on icon sets updater script, that wasn't such a good idea. Version 3 doesn't fix any bugs, but it did introduce a new bug: plugin for replacing ids no longer works correctly.

It will stay as beta until SVGO 3 bugs are fixed or I'll add workarounds for those bugs.

**Comment by cyberalien** [comment]
Fixed all issues with SVGO 3, released 2.2.0 as stable.
