### ISSUE TITLE
@Iconify/tools isnot compatible with vite-plugin-dynamic-import

### ISSUE THREAD

**Issue by amirtbi** [iconify/tools#24]
I use vite-plugin-dynamic-import in my Vue+Vite project. and also, the @iconify-vue is used. During the build of project, the following error appears:

> 'promises' is not exported by __vite-browser-external, imported by node_modules/@iconify/tools/lib/misc/scan.mjs

apparently , the @iconify/tool is not compatible with the plugin. 

How can handle this issue?

**Comment by amirtbi** [comment]
> Also that file should not be bundled. `@iconify/tools` package is server only, not for bundles.

I also 

> You are probably using old version of Node or `@types/node`
I use latest version of both of them. It fails during build

**Comment by cyberalien** [comment]
Are you attempting to bundle it for browser?

**Comment by amirtbi** [comment]
> Are you attempting to bundle it for browser?

I just run the command "npm run build" in Vite. It worked well, but when i used the vite-plugin-dynamic-import, this issue occured. Also, it has not any problems during runnnig  'npm run dev'

**Comment by cyberalien** [comment]
What environment are you bundling for? Node or browser?

**Comment by amirtbi** [comment]
> 

Yes, the vite-plugin-dynamic-import has bug when Vite using this plugin. 
Thakns.
