### ISSUE TITLE
How do I export all icons within an Iconify JSON file to SVG?

### ISSUE THREAD

**Issue by fmotion1** [iconify/tools#28]
I've been going through the docs and I can't find a demonstration for this scenario. I have an Iconify JSON set (solar), and I want to extract all icons to a directory in SVG format. How can I accomplish this? Can someone link me to the documentation that shows this process?

**Comment by cyberalien** [comment]
This example shows how to export icon set: https://iconify.design/docs/libraries/tools/export/directory.html

But first you need to import it to IconSet class instance, this example shows how to import it: https://iconify.design/docs/libraries/tools/import/json.html
