### ISSUE TITLE
Could you add a example about how use in Node env

### ISSUE THREAD

**Issue by fengchuanBIG** [iconify/tools#30]
Could you add a example about how use in Node env

**Comment by cyberalien** [comment]
There are examples in documentation: https://iconify.design/docs/libraries/tools/

**Comment by fengchuanBIG** [comment]
<img width="1439" alt="截屏2023-08-23 14 59 55" src="https://github.com/iconify/tools/assets/35793306/0f681706-bc79-406a-8e8e-516e77a6d686">

**Comment by fengchuanBIG** [comment]
It will report an error when it runs

**Comment by cyberalien** [comment]
Looks like you are using old CommonJS modules and not using TypeScript. In that case you need to change imports to `require()`.

Code samples are intended for modern development environments, either using ES modules or TypeScript.

**Comment by fengchuanBIG** [comment]
I still don't know how to deal with it, it's kind of hard

**Comment by cyberalien** [comment]
Replace first lines with this:
```js
const fs = require('fs/promises');
const { importDirectory } = require('@iconify/tools/lib/import/directory');
const { cleanupSVG } = require('@iconify/tools/lib/svg/cleanup');
const { runSVGO } = require('@iconify/tools/lib/optimise/svgo');
const { parseColors, isEmptyColor } = require('@iconify/tools/lib/colors/parse');
```

**Comment by cyberalien** [comment]
Then revert code. Looks like you have changed `module` property in package.json, so you no longer need to change first lines.

Or maybe you are using outdated version of Node? Check version by typing `node --version`, if it is below 18, update it.

**Comment by fengchuanBIG** [comment]
My nodejs version is v18.17.1

**Comment by fengchuanBIG** [comment]
<img width="1680" alt="截屏2023-08-23 15 44 08" src="https://github.com/iconify/tools/assets/35793306/4b883bea-ba1d-474e-9c38-e36885b07841">
How should I deal with it? Do I need to reconfigure the environment?

**Comment by fengchuanBIG** [comment]
<img width="1678" alt="截屏2023-08-23 15 45 44" src="https://github.com/iconify/tools/assets/35793306/66740400-f029-431c-8d6e-b331efc03da8">

**Comment by cyberalien** [comment]
I have no idea what's going on in your environment. That import should work. I just tested it, works fine.

**Comment by fengchuanBIG** [comment]
<img width="1489" alt="截屏2023-08-23 16 05 17" src="https://github.com/iconify/tools/assets/35793306/bf2b78f8-645a-402d-b7b0-26814db3b18b">
I reopened the new folder, but it still keeps reporting errors, I need your help 😭

**Comment by cyberalien** [comment]
Can you post contents of your `package.json`?

**Comment by fengchuanBIG** [comment]
{
	"name": "iconify-tools",
	"description": "Collection of functions for cleaning up and parsing SVG for Iconify project",
	"author": "Vjacheslav Trushkin",
	"license": "MIT",
	"private": true,
	"bugs": "https://github.com/iconify/tools/issues",
	"homepage": "https://github.com/iconify/tools",
	"repository": {
		"type": "git",
		"url": "git://github.com/iconify/tools.git"
	},
	"workspaces": [
		"@iconify/*",
		"@debug/*",
		"@iconify-demo/*"
	],
	"packageManager": "pnpm@8.6.11",
	"scripts": {
		"build": "pnpm recursive run build",
		"test": "pnpm recursive run test",
		"lint": "pnpm recursive run lint",
		"build:tools": "pnpm recursive --filter \"./@iconify/tools\" run build",
		"test:tools": "pnpm recursive --filter \"./@iconify/tools\" run test:ci",
		"lint:tools": "pnpm recursive --filter \"./@iconify/tools\" run lint"
	}
}

**Comment by cyberalien** [comment]
What are you doing? Why did you copy package.json from this repository?

**Comment by fengchuanBIG** [comment]
<img width="1492" alt="image" src="https://github.com/iconify/tools/assets/35793306/954b2bd1-2c0c-49bd-8e9b-a2a1609526b9">

**Comment by fengchuanBIG** [comment]
Isn't it a direct copy of the case?

**Comment by fengchuanBIG** [comment]
{
	"name": "iconify-tools",
	"description": "Collection of functions for cleaning up and parsing SVG for Iconify project",
	"author": "Vjacheslav Trushkin",
	"license": "MIT",
	"private": true,
	"bugs": {
		"url": "https://github.com/iconify/tools/issues"
	},
	"homepage": "https://github.com/iconify/tools",
	"repository": {
		"type": "git",
		"url": "git://github.com/iconify/tools.git"
	},
	"workspaces": [
		"@iconify/*",
		"@debug/*",
		"@iconify-demo/*"
	],
	"packageManager": "pnpm@8.6.11",
	"scripts": {
		"build": "pnpm recursive run build",
		"test": "pnpm recursive run test",
		"lint": "pnpm recursive run lint",
		"build:tools": "pnpm recursive --filter \"./@iconify/tools\" run build",
		"test:tools": "pnpm recursive --filter \"./@iconify/tools\" run test:ci",
		"lint:tools": "pnpm recursive --filter \"./@iconify/tools\" run lint"
	},
	"dependencies": {
		"@iconify/tools": "file:@iconify/tools",
		"axios": "^1.4.0"
	},
	"version": "1.0.0",
	"main": "fc.js",
	"devDependencies": {},
	"keywords": []
}

**Comment by fengchuanBIG** [comment]
This is the configuration of the previous version

**Comment by cyberalien** [comment]
So you've cloned this repository? That's not how packages are used in Node.js.

This repository is a source monorepo, not a template. You need to create new project, install `@iconify/tools` as dependency, then use it in your scripts.

See tutorials on how to create new Node.js project. There should be plenty of videos on Node.js basics on YouTube.

**Comment by fengchuanBIG** [comment]
Got it, I'll give it a try first, I use the repository as a template. . .

**Comment by fengchuanBIG** [comment]
<img width="1497" alt="image" src="https://github.com/iconify/tools/assets/35793306/7b2b1589-bfaf-4f95-8773-c20edc4fa8d6">
It was successful, but why is there no svg output?

**Comment by cyberalien** [comment]
It cannot import that icon because it cannot extract icon name from it. 

See https://iconify.design/docs/icons/icon-basics.html#icon-names

**Comment by fengchuanBIG** [comment]
Found the problem, the icon name does not support the Chinese name

**Comment by fengchuanBIG** [comment]
![werwrw](https://github.com/iconify/tools/assets/35793306/e38bb4d8-32cb-478b-b8ed-d03713fcdc0e)
![yiu](https://github.com/iconify/tools/assets/35793306/70c480a9-974a-42fa-9145-b7717149ef3a)
{
	"prefix": "test",
	"lastModified": 1692782435,
	"icons": {
		"werwrw": {
			"body": "<path fill=\"currentColor\" d=\"m512 738.133-286.72-286.72-45.227 45.227 286.72 286.72L512 828.587l45.227-45.227 286.72-286.72-45.227-45.227L512 738.133z\"/><path fill=\"currentColor\" d=\"m512 572.587 45.227-45.227 286.72-286.72-45.227-45.227L512 482.133l-286.72-286.72-45.227 45.227 286.72 286.72L512 572.587z\"/>",
			"width": 1024
		},
		"yiu": {
			"body": "<path fill=\"currentColor\" d=\"M229.578 936.003A510.016 510.016 0 10796.425 87.977a510.016 510.016 0 10-566.847 848.026Z\"/><path fill=\"currentColor\" d=\"M576.774 193.214V320.77H449.217v-85.038H279.14a21.26 21.26 0 010-42.52h170.076a42.519 42.519 0 0185.038 0z\"/><path fill=\"currentColor\" d=\"M780.653 386.675h-21.26c-4.89-55.487-19.346-94.605-44.007-119.053-34.44-34.228-85.038-36.141-138.4-35.716v-21.26c56.126 0 113.101 2.126 153.282 42.52 28.275 27.637 45.07 71.644 50.385 133.51z\" opacity=\".9\"/><path fill=\"currentColor\" d=\"M831.888 599.27H704.331l16.582-148.816a47.196 47.196 0 0115.307-29.976v-33.803H800v33.59a47.196 47.196 0 0115.307 29.976zM470.476 299.511h85.038a127.557 127.557 0 01127.557 127.557V788.48a42.519 42.519 0 01-42.519 42.519H385.438a42.519 42.519 0 01-42.519-42.52V427.07a127.557 127.557 0 01127.557-127.56z\"/><path fill=\"currentColor\" d=\"M342.92 490.847h340.15v127.557H342.92z\"/><path fill=\"currentColor\" d=\"M342.92 533.366h340.15v42.519H342.92z\"/>",
			"width": 1029
		}
	},
	"height": 1024
}

**Comment by fengchuanBIG** [comment]
I tried it yesterday. After processing the above two icons, I got the corresponding json, but it cannot be displayed. Can you help me to take a look, because I am not sure if the format is wrong.

**Comment by fengchuanBIG** [comment]
I found the problem, the viewbox is not defined, but how can I keep the color? I'm still trying. By the way, I am just a designer, my code level is very limited 😶

**Comment by fengchuanBIG** [comment]
I'm trying to keep the icons of multiple colors, because they all become a single color after processing

**Comment by fengchuanBIG** [comment]
Can you support the stroke-width attribute? Some icons have this attribute. It would be even better if it could be supported.

**Comment by fengchuanBIG** [comment]
It seems that you need to manually remove the stroke-width attribute inside, and then you can customize it. That is, can you customize whether to clear these when clearing?

**Comment by fengchuanBIG** [comment]
How do you guys keep the colors?

**Comment by fengchuanBIG** [comment]
Solved, read the documentation and found that such a function is provided
