### ISSUE TITLE
Unocss vscode plugin not working after adding custom icons

### ISSUE THREAD

**Issue by MarvinXu** [iconify/tools#43]
I tried loading custom svg from directory  using code from your demo: https://github.com/iconify/tools/tree/main/%40iconify-demo/unocss

but after adding this config, my unocss plugin doesn't work anymore. 

![image](https://github.com/user-attachments/assets/da784ea8-c024-434b-a17b-b9a3df385d52)

After commenting out custom collection, the plugin works again.
![image](https://github.com/user-attachments/assets/2ce13f58-635d-4152-a564-7cba86bda8bb)

**Comment by userquin** [comment]
Can you try adding `block` to icon class?

**Comment by MarvinXu** [comment]
Do you mean this?
![image](https://github.com/user-attachments/assets/ca7503c6-8769-4dc0-82e6-cddea34bfcc7)
Still no unocss tooltip

**Comment by userquin** [comment]
are svg present in the dom?

**Comment by MarvinXu** [comment]
This should be a bug of unocss vscode plugin [#4200](https://github.com/unocss/unocss/issues/4200)
