### ISSUE TITLE
What to return in a promiseEach?

### ISSUE THREAD

**Issue by arjendejong12** [iconify/tools#8]
Hi there,

I'm trying to import the FontAwesome Duotone icons where I'm replacing the classes. I'm using your conversion script ([link](https://github.com/iconify/iconify/issues/4#issuecomment-488833665)) but I've added the following `then()`:

```js
}).then(() => {

        // Replace duotone classes
        if (prefix === 'fad') {
            return collection.promiseEach(svg => {
                let string = svg.toString();
                string = string.replace('fa-primary', 'icon-primary').replace(/fa-secondary/g, 'icon-secondary');
                console.log(string);
                svg = new tools.SVG(string);
                return svg;
            });
        }

    }).then(() => {
```
However, I'm getting the following error:
```js
TypeError: func.then is not a function
    at next (/srv/www/m/mediasoep.nl/vhosts/iconify/htdocs/node_modules/@iconify/tools/src/collection.js:352:22)
    at /srv/www/m/mediasoep.nl/vhosts/iconify/htdocs/node_modules/@iconify/tools/src/collection.js:377:13
    at new Promise (<anonymous>)
    at Collection.promiseEach (/srv/www/m/mediasoep.nl/vhosts/iconify/htdocs/node_modules/@iconify/tools/src/collection.js:326:16)
```
When I change the return line to `return tools.SVGO(svg);`, it works correctly. But I don't want to use any tool from the tools to fix this. What do I return instead?

**Comment by cyberalien** [comment]
You need to return Promise instance.

promiseEach runs a Promise instance for each icon, similar to Promise.all(), but with one big difference that promises are ran one after another which is much better for processing many icons with async functions.

However for your use its better to use forEach() instead of promiseEach() and modify existing instance instead of replacing it:
```js
collection.forEach(svg => {
   svg.load(svg.toString().replace(/fa-primary/g, 'icon-primary').replace(/fa-secondary/g, 'icon-secondary'));
});
```

**Comment by arjendejong12** [comment]
Thanks, that solved my problem! Continuing on Duotone icons, my custom api returns the SVG without the `<defs><style>.fa-secondary{opacity:.4}</style></defs>` and the first `<path>` doesn't have that class, but has the `opacity` attribute. How can I get the api to return that data? Check this icon for example: https://iconify.mediasoep.nl/fad:award.svg

**Comment by cyberalien** [comment]
What code did you use for optimisation?

**Comment by arjendejong12** [comment]
I found the cause, it's because I optimize the svgs with SVGO. Removing that fixes my problem!
