### ISSUE TITLE
How to add or override SVGO plugins object?

### ISSUE THREAD

**Issue by iamazik** [iconify/tools#9]
I don't see a way to add more SVGO plugins or override the defined plugins in the `plugins[]` array. How do I do that?

https://github.com/iconify/tools/blob/04fea91305a7ce6932856558aa8f04ec25a20db9/src/optimize/svgo.js#L48

I want to define more SVGO plugins like `removeAttrs: {attrs: '(class)'}` to remove classes and optimise the way I'd like. How do I go about doing that, please?

**Comment by cyberalien** [comment]
That's a good idea.

I've added "plugins" option to SVGO where you can set custom plug-ins. If that option is set, other options that change plugins list are ignored, so you have full control over plugins list.

**Comment by iamazik** [comment]
Added https://github.com/iconify/tools/commit/0feb8607487e215a21485c765b74a875c77d4ed8

**Comment by iamazik** [comment]
Thanks for the prompt update on this @cyberalien. I really appreciate this. However, I couldn't make it work unless I am missing something here. There's must be something funky going on here:

`parse.js`
```javascript
const plugins = [
    {removeDimensions: true}
]

tools.ImportDir(sourceDir).then(result => {
    collection = result;
    console.log(`Found ${collection.length()} icons`);

    return collection.promiseAll(svg => {
        tools.SVGO(svg, plugins)
    }).then(() => {
        tools.ExportDir(collection, 'optimized/svg')
    })
})
```

It didn't work. So, I tried with the following and that neither work:

```javascript
const options= {
    plugins: [
        {removeDimensions: true}
    ]
}

tools.ImportDir(sourceDir).then(result => {
    collection = result;
    console.log(`Found ${collection.length()} icons`);

    return collection.promiseAll(svg => {
        tools.SVGO(svg, options)
    }).then(() => {
        tools.ExportDir(collection, 'optimized/svg')
    })
})
```

I am expecting the output to remove the `width` and `height` from the optimized `.svg` files. However, it's not working as expected. When checking the `svgo.js` again and `console.log()` the `options`, the output isn't as expected.

After digging a bit further, I see the property you have just added `'plugins': null,` isn't actually populating at all with the custom plugins passed from the `SVGO()` instance.

Anything I am missing here?

**Comment by cyberalien** [comment]
I've just tested it (and added unit tests, which I forgot to add when publishing update), custom plugins works fine.

Issue with dimensions isn't caused by SVGO. It is caused by export function. See `src/svg.js`:
```js

		// Add missing viewBox attribute
		if ($root.attr('viewBox') === void 0) {
			$root.attr(
				'viewBox',
				this.left + ' ' + this.top + ' ' + this.width + ' ' + this.height
			);
		}

		// Add missing width/height
		if ($root.attr('width') === void 0) {
			$root.attr('width', this.width);
		}
		if ($root.attr('height') === void 0) {
			$root.attr('height', this.height);
		}
```

This is not a bug, it is intended. SVG without width, height or viewBox is rendered incorrectly in some software. It is supposed to work, but unfortunately there are some bad SVG parsers that require redundancy. It has been a while since I've tested it, so I don't remember what software had issues with it.

**Comment by iamazik** [comment]
Yeah, right. Some software doesn't take care of the `width` and `height` by default. In that case, can not we extract the _Add missing viewBox attributes_ separately and use this as an optional property? In this way, whoever needs this can chain this optional property/method while exporting/optimizing.
